### ISSUE TITLE
o2s connection refused

### ISSUE THREAD

**Issue by Dannyzen** [padelt/docker-owntracks-private-mqtt-broker#1]
Hey there, 
I've followed the directions in the README.md and am receiving the below error after running `./start.sh`:

```
016-04-06 17:45:40,659 INFO spawned: 'o2s' with pid 486
2016-04-06 17:45:48,669 INFO success: o2s entered RUNNING state, process has stayed up for > than 8 seconds (startsecs)
2016-04-06 17:45:50,867 DEBG 'o2s' stderr output:
Connect to `localhost:8883': [Errno 111] Connection refused
```

Any thoughts around what I may have done incorrectly?

**Comment by padelt** [comment]
I am afraid I missed some changes on the last push. Please `git pull` again, `docker build` and then start with an empty userdata directory!
